emit:
  - "@typespec/openapi3"
  # - "@typespec/json-schema"

options:
  # "@typespec/json-schema":
  #   file-type: json
  #   emitAllModels: true
  "@typespec/openapi3":
    file-type: json
    # emitAllModels: true
